apiVersion: 1

deleteDatasources:
#  - name: Prometheus for Chaos Monkey
#    orgId: 1

datasources:
  - name: Prometheus for Chaos Monkey
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true